menubar:
  columns: 4
  items:
    - id: home
      theme: ''
      title: 主页
      icon: ''
      url: /
    - id: links
      theme: ''
      title: 友链
      icon: ''
      url: /links
    - id: services
      theme: ''
      title: 服务
      icon: ''
      url: /services
    - id: about
      theme: ''
      title: 关于
      icon: ''
      url: /about

footer:
  social:
    rss:
      icon: '<img src="https://p.sda1.dev/23/e0791e4a24490bf3d320a84e7549b07d/social_style_3_rss-512-1.png"/>'
      url: /atom.xml
      
rss: /atom.xml
